
%% Add make adjustments. For instance you add the following line to add fuserl
%% to the makepath for systools:make_script/1
%% [{code,add_patha,["/home/qluclar/packages/fuserl/lib/erlang/lib/fuserl-2.0.5/ebin/"]}].

[].
